name: sneaker_store_mobile_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.1.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  provider: ^5.0.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.2.1
  intl: ^0.18.1
  fl_chart: ^0.65.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/pic/
