version: "3"
name: back_office_v2
networks:
  net6:

services:
  db:
    networks:
      - net6
    image: mariadb:latest
    restart: always
    ports:
      - "3307:3306" # External port changed to 3307
    environment:
      MYSQL_TCP_PORT: 3306
      MYSQL_DATABASE: backOfficeV2
      MYSQL_ROOT_PASSWORD: "root" # Updated root password for clarity
    volumes:
      - ./db_v2:/data/db
      - ./db_v2/db2.sql:/docker-entrypoint-initdb.d/db.sql

  adminer:
    networks:
      - net6
    image: adminer
    restart: always
    ports:
      - 2002:8080 # External port changed to 2002
    depends_on:
      - db

  # New service to handle image uploads
  image_storage:
    networks:
      - net6
    image: nginx:latest # You can use any image or even a custom one for your app
    volumes:
      - ./images:/app/images # Mount local 'images' directory to '/app/images' in container
    ports:
      - "8080:80" # Expose a port for testing (optional)
